name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test 1
      id: test-1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test 1
        setup-command: ''
        command: PROJECT_DIR=$(dirname $(find . -name "angular.json" | head -n 1));
          cd "$PROJECT_DIR" && curl -sL https://gist.github.com/quocthang0507/ca5c78467e1b278a5ce6817e6f29406d/raw/de7f935e9331efb7405cbde0ddacfebbb0f80ed2/Test1.ts
          -o src/app/services/todo.service.spec.ts && npm install && npx ng build
          && npx ng test --include src/app/services/todo.service.spec.ts --no-watch
          --browsers=ChromeHeadless
        timeout: 10
        max-score: 3
    - name: Test 2
      id: test-2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test 2
        setup-command: ''
        command: PROJECT_DIR=$(dirname $(find . -name "angular.json" | head -n 1));
          cd "$PROJECT_DIR" && curl -sL https://gist.github.com/quocthang0507/ca5c78467e1b278a5ce6817e6f29406d/raw/de7f935e9331efb7405cbde0ddacfebbb0f80ed2/Test2.ts
          -o src/app/home/home.page.spec.ts && npx ng test --include src/app/home/home.page.spec.ts
          --no-watch --browsers=ChromeHeadless
        timeout: 2
        max-score: 2
    - name: Test 3
      id: test-3
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test 3
        setup-command: ''
        command: PROJECT_DIR=$(dirname $(find . -name "angular.json" | head -n 1));
          cd "$PROJECT_DIR" && curl -sL https://gist.github.com/quocthang0507/ca5c78467e1b278a5ce6817e6f29406d/raw/de7f935e9331efb7405cbde0ddacfebbb0f80ed2/Test3.ts
          -o src/app/settings/settings.page.spec.ts && npx ng test --include src/app/settings/settings.page.spec.ts
          --no-watch --browsers=ChromeHeadless
        timeout: 2
        max-score: 3
    - name: Test 4
      id: test-4
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test 4
        setup-command: ''
        command: PROJECT_DIR=$(dirname $(find . -name "angular.json" | head -n 1));
          cd "$PROJECT_DIR" && curl -sL https://gist.github.com/quocthang0507/ca5c78467e1b278a5ce6817e6f29406d/raw/de7f935e9331efb7405cbde0ddacfebbb0f80ed2/Test4.ts
          -o src/app/home/home.page.advanced.spec.ts && npx ng test --include src/app/home/home.page.advanced.spec.ts
          --no-watch --browsers=ChromeHeadless
        timeout: 2
        max-score: 2
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-1_RESULTS: "${{steps.test-1.outputs.result}}"
        TEST-2_RESULTS: "${{steps.test-2.outputs.result}}"
        TEST-3_RESULTS: "${{steps.test-3.outputs.result}}"
        TEST-4_RESULTS: "${{steps.test-4.outputs.result}}"
      with:
        runners: test-1,test-2,test-3,test-4
